### ISSUE TITLE
[LOC]

### ISSUE THREAD

**Issue by SantinoIannuzzi** [northwesttrees-gaming/NWTG-Automation#12]
> ## NOTE
> Use the template from this page below for your translation.
> https://github.com/northwesttrees-gaming/NWTG-Automation/wiki/EN-Localization
> Add two spaces at the end of the second line to make a third line. 
> Then under the second line add your translation for that localization key.
> DO NOT UPDATE CLOSED ISSUES MAKE A NEW ISSUE FOR IF IT BECOMES CLOSED.

## LANGUAGE
( LIST THE LANGUAGE HERE )

## TRANSLATED LOCALIZATION TEMPLATE
( PASTE THE LOCALIZATION TEMPLATE HERE AND TRANSLATE THE SECOND LINE  ON THE THIRD LINE )

**Comment by SantinoIannuzzi** [comment]
> ## NOTE
> Use the template from this page below for your translation.
> https://github.com/northwesttrees-gaming/NWTG-Automation/wiki/EN-Localization
> Add two spaces at the end of the second line to make a third line. 
> Then under the second line add your translation for that localization key.
> DO NOT UPDATE CLOSED ISSUES MAKE A NEW ISSUE FOR IF IT BECOMES CLOSED.

## LANGUAGE
Spanish Argentina

## TRANSLATED LOCALIZATION TEMPLATE
## BLOCKS

* block.nwtg_automation.grass_block_slab_lower  
Losa de bloque de pasto inferior
 
* block.nwtg_automation.machine_block  
Bloque máquina
  
* block.nwtg_automation.grass_block_slab_upper  
Losa de bloque de pasto superior

## CREATIVE TABS

* itemGroup.tabnwtg_automation_tab  
NWTG Automation

## DEVICES

* block.nwtg_automation.breaker_panel  
Panel de interruptores
  
* block.nwtg_automation.breaker_panel_on  
Panel de interruptores encendido
  
* block.nwtg_automation.remote_item_teleporter  
Objeto de teletransporte remoto

## ENERGY DEVICES

* block.nwtg_automation.battery  
Batería
  
* block.nwtg_automation.battery_on  
Batería encendida
  
* block.nwtg_automation.power_hub  
Centro de alimentación
  
* block.nwtg_automation.solar_panel  
Panel solar
  
* block.nwtg_automation.solar_panel_idle  
Panel solar ocioso
  
* block.nwtg_automation.solar_panel_on  
Panel solar encendido

## MACHINES

* block.nwtg_automation.auto_crafting_machine  
Máquina de crafteo
  
* block.nwtg_automation.auto_crafting_machine_on  
Máquina de crafteo encendida
  
* block.nwtg_automation.auto_farming_machine  
Máquina de cosecha y cultivo
  
* block.nwtg_automation.auto_farming_machine_on  
Máquina de cosecha y cultivo encendida
  
* block.nwtg_automation.auto_item_collector_machine  
Máquina de recolección
  
* block.nwtg_automation.auto_item_collector_machine_on  
Máquina de recolección encendida
  
* block.nwtg_automation.auto_tree_farm_machine  
Máquina de cosecha y cultivo de árboles
  
* block.nwtg_automation.auto_tree_farm_machine_on  
Máquina de cosecha y cultivo de árboles encendida

## SUBTITLES

* subtitles.switch_off  
Cambió a apagado
  
* subtitles.switch_on  
Cambió a encendido

## TOOLS

* item.nwtg_automation.machine_wrench  
Llave inglesa para máquinas

## UPGRADES

* item.nwtg_automation.diamond_upgrade  
Mejora de diamante
  
* item.nwtg_automation.golden_upgrade  
Mejora de oro
  
* item.nwtg_automation.iron_upgrade  
Mejora de hierro
  
* item.nwtg_automation.netherite_upgrade  
Mejora de netherita
  
* item.nwtg_automation.stone_upgrade  
Mejora de piedra
  
* item.nwtg_automation.wooden_upgrade  
Mejora de madera

## WOODEN LAMPS
* block.nwtg_automation.acacia_lamp  
Lámpara de acacia

* block.nwtg_automation.acacia_lamp_on  
Lámpara de encendida
  
* block.nwtg_automation.birch_lamp  
Lámpara de abedul
  
* block.nwtg_automation.birch_lamp_on  
Lámpara de abedul encendida
  
* block.nwtg_automation.crimson_lamp  
Lámpara carmesí
  
* block.nwtg_automation.crimson_lamp_on  
Lámpara carmesí encendida
  
* block.nwtg_automation.dark_oak_lamp  
Lámpara de roble oscuro
  
* block.nwtg_automation.dark_oak_lamp_on  
Lámpara de roble oscuro encendida
  
* block.nwtg_automation.jungle_lamp  
Lámpara de jungla
  
* block.nwtg_automation.jungle_lamp_on  
Lámpara de jungla encendida
  
* block.nwtg_automation.oak_lamp  
Lámpara de roble
  
* block.nwtg_automation.oak_lamp_on  
Lámpara de roble encendida
  
* block.nwtg_automation.spruce_lamp  
Lámpara de abeto
  
* block.nwtg_automation.spruce_lamp_on  
Lámpara de abeto encendida
  
* block.nwtg_automation.warped_lamp  
Lámpara deformada
  
* block.nwtg_automation.warped_lamp_on  
Lámpara deformada encendida

* msg.nwtg_automation.acacia_lamp.linked_to_breaker_panel  
La lámpara de acacia ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.acacia_lamp.linked_to_power_hub  
La lámpara de acacia ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.birch_lamp.linked_to_breaker_panel  
La lámpara de abedul ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.birch_lamp.linked_to_power_hub  
La lámpara de abedul ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.crimson_lamp.linked_to_breaker_panel  
La lámpara carmesí ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.crimson_lamp.linked_to_power_hub  
La lámpara carmesí ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.dark_oak_lamp.linked_to_breaker_panel  
La lámpara de roble oscuro ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.dark_oak_lamp.linked_to_power_hub  
La lámpara de roble oscuro ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.jungle_lamp.linked_to_breaker_panel  
La lámpara de jungla ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.jungle_lamp.linked_to_power_hub  
La lámpara de jungla ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.oak_lamp.linked_to_breaker_panel  
La lámpara de roble ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.oak_lamp.linked_to_power_hub  
La lámpara de roble ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.spruce_lamp.linked_to_breaker_panel  
La lámpara de abeto ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.spruce_lamp.linked_to_power_hub  
La lámpara de abeto ahora está enlazada a el centro de alimentación en:
  
* msg.nwtg_automation.warped_lamp.linked_to_breaker_panel  
La lámpara deformada ahora está enlazada al panel de interruptores en:
  
* msg.nwtg_automation.warped_lamp.linked_to_power_hub  
La lámpara deformada ahora está enlazada a el centro de alimentación en:

**Comment by northwesttreesgaming** [comment]
Thank you a tone <3
